name: Build LaTeX Document
on: [push, pull_request]
jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          compiler: xelatex
      - name: Upload PDF
        uses: actions/upload-artifact@v1
        with:
          name: PDF
          path: main.pdf
